/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApiPublicBootstrapUsersRouteImport } from './routes/api/public/bootstrap-users'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapUsersRoute = ApiPublicBootstrapUsersRouteImport.update({
  id: '/api/public/bootstrap-users',
  path: '/api/public/bootstrap-users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRoute
  '/api/public/bootstrap-users': typeof ApiPublicBootstrapUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRoute
  '/api/public/bootstrap-users': typeof ApiPublicBootstrapUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRoute
  '/api/public/bootstrap-users': typeof ApiPublicBootstrapUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/bootstrap-users'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/bootstrap-users'
  id: '__root__' | '/_authenticated' | '/api/public/bootstrap-users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRoute
  ApiPublicBootstrapUsersRoute: typeof ApiPublicBootstrapUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-users': {
      id: '/api/public/bootstrap-users'
      path: '/api/public/bootstrap-users'
      fullPath: '/api/public/bootstrap-users'
      preLoaderRoute: typeof ApiPublicBootstrapUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRoute,
  ApiPublicBootstrapUsersRoute: ApiPublicBootstrapUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
